# Generated by Django 4.0.3 on 2022-03-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('purity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_app.breed')),
            ],
        ),
    ]
