# Generated by Django 4.0.3 on 2022-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rabbit',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
